name: Deploy Lambda Function

env:
  ARTIFACT_NAME: lambda_function.zip
  AWS_REGION: us-east-1

on:
  push:
    branches: [ main ]

jobs:
  Lambda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y zip unzip
          npm install dotenv

      
      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID}}
          aws-region: ${{ env.AWS_REGION }}

      - name: zip  Lambda files
        run : zip csye6225-lambda-${{ github.sha}}.zip email.js
      - name: Upload Zip to S3
        run: |
            aws s3 cp ./csye6225-lambda-${{ github.sha}}.zip s3://${{ secrets.LAMBDA_BUCKET }}/
            
      - name: Update Function Code
        run: |
            aws lambda update-function-code --function-name verify_email --s3-bucket ${{ secrets.LAMBDA_BUCKET }} --s3-key csye6225-lambda-${{ github.sha}}.zip

